services:
  borgserver:
    container_name: ${BORGSERVER_NAME:-borgserver}
    image: nold360/borgserver:${BORGSERVER_VERSION:-latest}
    restart: ${BORGSERVER_RESTART:-unless-stopped}
    environment:
      TZ: ${BORGSERVER_TZ:-America/Chicago}
      PUID: ${BORGSERVER_PUID}
      PGID: ${BORGSERVER_PGID}
    ports:
      - "${BORGSERVER_SSH_PORT}:22"
    volumes:
      - "${CONTAINER_DATA}/borgserver:/sshkeys"
      - "${BORGSERVER_BACKUP_DIR}:/backup"
