services:
  quay-clair-postgresql:
    container_name: quay-clair-postgresql
    image: postgres:17-alpine
    restart: unless-stopped
    networks:
      - ${NETWORK_BACKEND:-backend}
    environment:
      TZ: ${TZ:-America/Chicago}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:-clairuser}
      POSTGRES_DB: ${POSTGRES_DB:-clair}
    volumes:
      - ${CONTAINER_DATA}/quay-clair-postgresql:/var/lib/postgresql/data:rw

  quay-clair:
    container_name: quay-clair
    image: quay.io/projectquay/clair:4.8.0
    restart: unless-stopped
    networks:
      - ${NETWORK_BACKEND:-backend}
    environment:
      TZ: ${TZ:-America/Chicago}
      CLAIR_MODE: ${CLAIR_MODE:-combo}
      CLAIR_CONF: ${CLAIR_CONF:-/config/config.yaml}
    volumes:
      - ${CONTAINER_DATA}/clair:/config:rw
    tmpfs:
      - /tmp
    depends_on:
      - quay-clair-postgresql

  quay-mirror:
    container_name: quay-mirror
    image: quay.io/projectquay/quay:3.15.2
    restart: unless-stopped
    networks:
      - ${NETWORK_FRONTEND:-frontend}
      - ${NETWORK_BACKEND:-backend}
    environment:
      TZ: ${TZ:-America/Chicago}
      IGNORE_VALIDATION: ${IGNORE_VALIDATION:-true}
    volumes:
      - ${CONTAINER_DATA}/quay/config/:/conf/stack:rw
      - ${CONTAINER_DATA}/quay:/datastorage:rw
    depends_on:
      - quay

  quay-postgresql:
    container_name: quay-postgresql
    image: postgres:17-alpine
    restart: unless-stopped
    networks:
      - ${NETWORK_BACKEND:-backend}
    environment:
      TZ: ${TZ:-America/Chicago}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:-quayuser}
      POSTGRES_DB: ${POSTGRES_DB:-quay}
    volumes:
      - ${CONTAINER_DATA}/quay-postgresql:/var/lib/postgresql/data:rw

  quay-redis:
    container_name: quay-redis
    image: redis
    restart: unless-stopped
    networks:
      - ${NETWORK_BACKEND:-backend}
    environment:
      TZ: ${TZ:-America/Chicago}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ${CONTAINER_DATA}/quay-redis:/data:rw
    command:
      - --save 60 1
      - --loglevel warning
      - --requirepass ${REDIS_PASSWORD}

  quay:
    container_name: quay
    image: quay.io/projectquay/quay:3.15.2
    restart: unless-stopped
    networks:
      - ${NETWORK_FRONTEND:-frontend}
      - ${NETWORK_BACKEND:-backend}
    environment:
      TZ: ${TZ:-America/Chicago}
      IGNORE_VALIDATION: ${IGNORE_VALIDATION:-true}
    volumes:
      - ${CONTAINER_DATA}/quay/config/:/conf/stack:rw
      - ${CONTAINER_DATA}/quay:/datastorage:rw
    depends_on:
      - quay-postgresql
      - quay-redis

networks:
  ${NETWORK_FRONTEND:-frontend}:
    external: ${NETWORK_EXTERNAL:-true}
  ${NETWORK_BACKEND:-backend}:
    external: ${NETWORK_EXTERNAL:-true}