services:
  tang:
    image: git.mcdade.app/containers/tang-server:latest
    container_name: tang
    restart: always
    ports:
      - "9099:80"
    volumes:
      - ${CONTAINER_DATA}:/var/db/tang
